# Numerical Python(Numpy) - Part 1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np

In [2]:
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x: x*3,a))

[3, 6, 9]

In [4]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [5]:
b*3

array([3, 6, 9])

## 1. Numpy Dimensional array

In [6]:
a= np.array([1,3,5,6], float)
a

array([1., 3., 5., 6.])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.dtype, a.shape

(dtype('float64'), (4,))

## 2. Array shape

In [9]:
# Vector(1차원)
vec = np.array([1,4,5,8])
print(vec.shape)
print(vec)

(4,)
[1 4 5 8]


In [10]:
# Matrix(2차원)
matr = np.array([[1,2,3],[4,5,6]])
print(matr.shape)
print(matr)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [11]:
# Tensor(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor.shape)
print(tensor)

(2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [12]:
vec.shape, matr.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [13]:
# element의 갯수
vec.size, matr.size, tensor.size

(4, 6, 24)

In [14]:
# data type
# float32: 32bit로 표시 - single precision
# float64: 64bit로 표시 - double precision
a=np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

In [15]:
a=np.array([1,2,3], np.float32)
a

array([1., 2., 3.], dtype=float32)

In [16]:
b=np.array([1,2,3], np.int16)
b

array([1, 2, 3], dtype=int16)

### reshape

In [17]:
matr = np.array([[1,2,3],[4,5,6]])
print(matr.shape)
matr

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
matr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
matr.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [20]:
matr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [21]:
matr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [22]:
# -1은 numpy가 알아서 맞춰줌 (단, size가 동일)
matr.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [23]:
matr.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
matr.reshape(3,-1).shape

(3, 2)

In [25]:
tensor.reshape(4,-1).shape

(4, 6)

### flatten

In [26]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [27]:
# 되긴 하는데 안 될 수도
tensor.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [28]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

### Indexing

In [29]:
matr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
matr[0][1]

2

In [31]:
matr[0,1]

2

In [32]:
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [33]:
tensor[1,1,2]

19

### Slicing

In [34]:
b= np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
# 5,6,9,10
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [36]:
# 5,6,7, 9,10,11
b[1:3, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [37]:
# 1,3,9,11
b[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [38]:
# X는 앞에 3열, y는 마지막 열
X, y = b[:,:-1], b[:,-1]
X.shape, y.shape

((4, 3), (4,))

In [39]:
X, y

(array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([ 3,  7, 11, 15]))

뭘까

- 해결 : 3번 블록은 오류가 나거나 2번 블록처럼 될 것이라 생각했지만 전혀 다른 결과가 나왔는데 예상되는 이유로는 4번 블록의 과정을 거쳐 5번 블록으로 이어지는 행 단위 슬라이싱의 연속으로 보인다

In [40]:
b= np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [42]:
b[1:3][1:3]

array([[ 8,  9, 10, 11]])

In [43]:
k=b[1:3,]
b[1:3,]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
k[1:3]

array([[ 8,  9, 10, 11]])

In [45]:
b[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
b[1:3,0:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])